[platformio]
default_envs = seeed_xiao_nrf52840_sense

[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git#ee406566f0f12d07f135f6ae846b86a8f62628b0
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3@2.0.7
build_flags =
    -DGOAT_SENSOR_PROTOCOL_VERSION=2
